//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;

// Type created for JSON at <<root>>
[DataContractAttribute()]
public partial class BinSensorReading
{
    
    [DataMemberAttribute()]
    public int sesnorID;
    
    [DataMemberAttribute()]
    public int binID;
    
    [DataMemberAttribute()]
    public string binName;
    
    [DataMemberAttribute()]
    public string binCategory;
    
    [DataMemberAttribute()]
    public double latitude;
    
    [DataMemberAttribute()]
    public double longitude;
    
    [DataMemberAttribute()]
    public int fillLevel;
    
    [DataMemberAttribute()]
    public double temperature;
    
    [DataMemberAttribute()]
    public int timestampdata;
}
