//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;

// Type created for JSON at <<root>>
[DataContractAttribute()]
public partial class SensorDetail
{
    
    [DataMemberAttribute()]
    public string status;
    
    [DataMemberAttribute()]
    public SensorDetailMessage message;
}

// Type created for JSON at <<root>> --> message
[DataContractAttribute(Name="message")]
public partial class SensorDetailMessage
{
    
    [DataMemberAttribute()]
    public int sensorsID;
    
    [DataMemberAttribute()]
    public int sensorstokenID;
    
    [DataMemberAttribute()]
    public string sensorCompany;
    
    [DataMemberAttribute()]
    public string sensorDeviceID;
    
    [DataMemberAttribute()]
    public string firmwareVersion;
    
    [DataMemberAttribute()]
    public string sensorName;
    
    [DataMemberAttribute()]
    public string isAllocated;
    
    [DataMemberAttribute()]
    public CurrentPinAllocated currentPinAllocated;
    
    [DataMemberAttribute()]
    public string description;
    
    [DataMemberAttribute()]
    public int heartbeatFrequency;
    
    [DataMemberAttribute()]
    public int companyID;
    
    [DataMemberAttribute()]
    public int createdDate;
    
    [DataMemberAttribute()]
    public int updatedDate;
    
    [DataMemberAttribute()]
    public int createdByUserID;
    
    [DataMemberAttribute()]
    public int updatedByUserID;
    
    [DataMemberAttribute()]
    public object latest_sensorsdata;
}

// Type created for JSON at <<root>> --> message --> currentPinAllocated
[DataContractAttribute(Name="currentPinAllocated")]
public partial class CurrentPinAllocated
{
    
    [DataMemberAttribute()]
    public int projectpinID;
    
    [DataMemberAttribute()]
    public int projectID;
    
    [DataMemberAttribute()]
    public string projectName;
    
    [DataMemberAttribute()]
    public int projectgroupID;
    
    [DataMemberAttribute()]
    public string groupName;
    
    [DataMemberAttribute()]
    public string iconType;
    
    [DataMemberAttribute()]
    public int iconID;
    
    [DataMemberAttribute()]
    public string iconURL;
    
    [DataMemberAttribute()]
    public int customlocationID;
    
    [DataMemberAttribute()]
    public string locationName;
    
    [DataMemberAttribute()]
    public string pinAddress1;
    
    [DataMemberAttribute()]
    public string pinAddress2;
    
    [DataMemberAttribute()]
    public string pinCity;
    
    [DataMemberAttribute()]
    public string pinState;
    
    [DataMemberAttribute()]
    public string pinCountry;
    
    [DataMemberAttribute()]
    public string pinZipCode;
    
    [DataMemberAttribute()]
    public double latitude;
    
    [DataMemberAttribute()]
    public double longitude;
    
    [DataMemberAttribute()]
    public string name;
    
    [DataMemberAttribute()]
    public string description;
    
    [DataMemberAttribute()]
    public string serialNumber;
    
    [DataMemberAttribute()]
    public object[] assetTag;
    
    [DataMemberAttribute()]
    public int manufacturerID;
    
    [DataMemberAttribute()]
    public string manufacturerName;
    
    [DataMemberAttribute()]
    public int createdDate;
    
    [DataMemberAttribute()]
    public int creatorUserID;
    
    [DataMemberAttribute()]
    public PinType pinType;
}

// Type created for JSON at <<root>> --> message --> currentPinAllocated --> pinType
[DataContractAttribute(Name="pinType")]
public partial class PinType
{
    
    [DataMemberAttribute()]
    public int pintypeID;
    
    [DataMemberAttribute()]
    public string pinTypeName;
    
    [DataMemberAttribute()]
    public string iconType;
    
    [DataMemberAttribute()]
    public int iconID;
    
    [DataMemberAttribute()]
    public string iconURL;
    
    [DataMemberAttribute()]
    public string pinTypeDescription;
    
    [DataMemberAttribute()]
    public string pinTypeImageOriginalName;
    
    [DataMemberAttribute()]
    public string pinTypeImageURL;
    
    [DataMemberAttribute()]
    public int manufacturerID;
    
    [DataMemberAttribute()]
    public string manufacturerName;
    
    [DataMemberAttribute()]
    public int pinTypeCreatedDate;
    
    [DataMemberAttribute()]
    public int pinTypeCreatedByUserID;
    
    [DataMemberAttribute()]
    public int pinTypeModifiedDate;
    
    [DataMemberAttribute()]
    public int pinTypeModifiedByUserID;
    
    [DataMemberAttribute()]
    public int depthWhenEmpty_cm;
    
    [DataMemberAttribute()]
    public int distanceSensorToFillLine_cm;
    
    [DataMemberAttribute()]
    public int total_projectpins;
}